### PR TITLE
adding code of conduct to pages folder

### PR DESCRIPTION
**Pull request by jdax**
An email or another form of contact needs to be added into this still. Let me know which email/s you would like included and I can put it in. Let me know if there are any other changes you would like. This is based off of a sample provided on geekfeminism's wikia.

### CODE REVIEW

**Comment by csexton** [comment]
I :heart: the content, thanks so much for doing this. :smiley_cat: 

Couple of minor changes before we merge:

### 1) Use markdown formatting for the list

Instead of:

```
<ul>
  <li>item 1</li>
  <li>item 2</li>

```

Lets use:

```
- item 1
- item 2
```

### 2) Move the file to the root dir and add yaml front matter

Move the file from `/_posts/codeofconduct.markdown` to `/codeofconduct.markdown`

And add the jekyll yaml "front matter" to the file, just like you can find in [`index.html`](https://github.com/arlingtonruby/retroruby.org/blob/gh-pages/index.html#L1-L4)

/ping @SeanMarcia

**Comment by seanmarcia** [comment]
No idea why I didn't get the notification on this but thanks so much for the PR!

**Comment by seanmarcia** [comment]
I think we have info@retroruby.org that gets sent to all the organizers? /cc @csexton

**Comment by csexton** [comment]
I am closing this in favor of using the COC we have at https://github.com/arlingtonruby/code-of-conduct. The new COC will cover both Ruby Retrocession and Arlington Ruby Meetup, and I wanted to have it in one central place as it needs to evolve and respond to the community.

Thanks for getting this started @jdax, and would love any input/pulls on that repo.

**Pull request closed without merging**
